# ==========================================================
# CONTEXT EXTRACTOR
# ==========================================================

import os
import re


class ContextExtractor:
    """
    Semantic context generation engine that processes impact results and aggregates relevant code,
    call graphs, and security metadata into a focused context package for consumption by AI agents.
    
    This engine extracts the precise code snippets of impacted functions, maps the caller
    execution chain paths, retrieves active route handlers, and traces taint flows associated
    with the blast radius, effectively pruning non-relevant code to optimize token usage.
    """

    # ======================================================
    # INIT
    # ======================================================

    def __init__(

        self,

        graph,

        project_root
    ):
        """
        Initializes the ContextExtractor with a compiled semantic graph and project root path.

        Args:
            graph (Dict): The full semantic context graph containing execution edges, definitions, and taints.
            project_root (str): The absolute path to the directory representing the workspace root.
        """

        self.graph = graph

        self.project_root = project_root

    # ======================================================
    # EXTRACT CONTEXT
    # ======================================================

    def extract_context(

        self,

        impact_result
    ):
        """
        Aggregates relevant files, functions, source code snippets, execution chains, route handlers,
        and taint flows into a unified context payload from raw impact analysis results.

        Args:
            impact_result (Dict): The results dictionary generated by the impact traversal engine,
                                 typically containing list keys like "affected_functions".

        Returns:
            Dict: A structured context dictionary containing keys:
                  - "relevant_files" (List[str])
                  - "relevant_functions" (List[Dict])
                  - "code_snippets" (List[Dict])
                  - "execution_chain" (List[Dict])
                  - "taint_flow" (List[Dict])
                  - "route_context" (List[Dict])
        """

        context = {

            "relevant_files": [],

            "relevant_functions": [],

            "code_snippets": [],

            "execution_chain": [],

            "taint_flow": [],

            "route_context": []
        }

        # ==================================================
        # AFFECTED FUNCTIONS
        # ==================================================

        affected_functions = impact_result.get(

            "affected_functions",

            []
        )

        if not affected_functions:
            seen = set()
            affected_functions = []

            def add_node(node):
                if not node:
                    return
                ntype = node.get("type")
                if ntype == "FUNCTION":
                    fpath = node.get("file")
                    fname = node.get("function")
                    if fpath and fname:
                        key = (fpath, fname)
                        if key not in seen:
                            seen.add(key)
                            affected_functions.append({
                                "file": fpath,
                                "function": fname
                            })
                elif ntype == "ROUTE":
                    fpath = node.get("file")
                    rpath = node.get("route")
                    rmethod = node.get("method")
                    if rpath and rmethod:
                        if not fpath:
                            # Resolve route file from graph routes schema
                            for fp, routes in self.graph.get("routes", {}).items():
                                for r in routes:
                                    if (r.get("path") == rpath and 
                                        r.get("method", "").lower() == rmethod.lower()):
                                        fpath = fp
                                        node["file"] = fp
                                        break
                                if fpath:
                                    break
                        if fpath:
                            import os
                            fpath = os.path.normpath(str(fpath)).replace("\\", "/")
                            if fpath not in context["relevant_files"]:
                                full_path = os.path.normpath(os.path.join(self.project_root, fpath))
                                if os.path.exists(full_path):
                                    context["relevant_files"].append(fpath)
                            
                            snippet = self.extract_route_statement(fpath, rpath, rmethod)
                            if snippet:
                                snippet_exists = False
                                for snip in context["code_snippets"]:
                                    if snip.get("file") == fpath and snip.get("function") == f"ROUTE {rmethod.upper()} {rpath}":
                                        snippet_exists = True
                                        break
                                if not snippet_exists:
                                    context["code_snippets"].append({
                                        "file": fpath,
                                        "function": f"ROUTE {rmethod.upper()} {rpath}",
                                        "code": snippet
                                    })
                elif ntype == "MIDDLEWARE":
                    fpath = node.get("file")
                    if fpath:
                        import os
                        fpath = os.path.normpath(str(fpath)).replace("\\", "/")
                        if fpath not in context["relevant_files"]:
                            full_path = os.path.normpath(os.path.join(self.project_root, fpath))
                            if os.path.exists(full_path):
                                context["relevant_files"].append(fpath)
                elif ntype == "DATABASE":
                    fpath = node.get("file")
                    model_name = node.get("model")
                    if fpath:
                        import os
                        fpath = os.path.normpath(str(fpath)).replace("\\", "/")
                        if fpath not in context["relevant_files"]:
                            full_path = os.path.normpath(os.path.join(self.project_root, fpath))
                            if os.path.exists(full_path):
                                context["relevant_files"].append(fpath)
                                try:
                                    with open(full_path, "r", encoding="utf-8") as f:
                                        file_content = f.read()
                                    snippet_exists = False
                                    for snip in context["code_snippets"]:
                                        if snip.get("file") == fpath and snip.get("function") == f"SCHEMA {model_name}":
                                            snippet_exists = True
                                            break
                                    if not snippet_exists:
                                        context["code_snippets"].append({
                                            "file": fpath,
                                            "function": f"SCHEMA {model_name}",
                                            "code": file_content
                                        })
                                except Exception as e:
                                    print(f"[ERROR extracting DATABASE schema]: {e}")

            target = impact_result.get("target")
            if isinstance(target, dict):
                add_node(target)
            elif isinstance(target, str):
                for fpath, funcs in self.graph.get("functions", {}).items():
                    for f in funcs:
                        if f.get("name") == target:
                            add_node({"type": "FUNCTION", "file": fpath, "function": target})

            for edge in impact_result.get("upstream", []) + impact_result.get("downstream", []):
                add_node(edge.get("from"))
                add_node(edge.get("to"))

        for item in affected_functions:

            file_path = item.get(

                "file"

            )

            function_name = item.get(

                "function"

            )

            if not file_path:
                continue

            # ==============================================
            # STORE FILE
            # ==============================================

            if (

                file_path

                not in

                context[
                    "relevant_files"
                ]
            ):
                full_path = os.path.normpath(os.path.join(self.project_root, file_path))
                if os.path.exists(full_path):
                    context[
                        "relevant_files"
                    ].append(file_path)

            # ==============================================
            # STORE FUNCTION
            # ==============================================

            context[
                "relevant_functions"
            ].append({

                "file": file_path,

                "function": function_name
            })

            # ==============================================
            # EXTRACT SNIPPET
            # ==============================================

            snippet = (
                self.extract_function_code(

                    file_path,

                    function_name
                )
            )

            if snippet:

                context[
                    "code_snippets"
                ].append({

                    "file": file_path,

                    "function": function_name,

                    "code": snippet
                })
                # ==============================================
                # EXECUTION CHAIN
                # ==============================================

                chain = self.extract_execution_chain(

                    file_path,

                    function_name
                )

                for item in chain:

                    if (

                        item

                        not in

                        context[
                            "execution_chain"
                        ]
                    ):

                        context[
                            "execution_chain"
                        ].append(item)

                # ==============================================
                # ROUTE CONTEXT
                # ==============================================

                routes = self.extract_route_context(

                    file_path,

                    function_name
                )

                for route in routes:

                    if (

                        route

                        not in

                        context[
                            "route_context"
                        ]
                    ):

                        context[
                            "route_context"
                        ].append(route)

                # ==============================================
                # TAINT FLOW
                # ==============================================

                taints = self.extract_taint_flow(
                    function_name
                )

                for item in taints:

                    if (

                        item

                        not in

                        context[
                            "taint_flow"
                        ]
                    ):

                        context[
                            "taint_flow"
                        ].append(item)

        return context

    # ======================================================
    # EXTRACT FUNCTION CODE
    # ======================================================

    def extract_function_code(
        self,
        relative_path,
        function_name
    ):
        """
        Reads a physical source file and extracts the exact string contents of the specified function
        using either pre-compiled graph metadata or AST-level node parsing.

        Args:
            relative_path (str): The workspace-relative file path containing the function.
            function_name (str): The name of the function to extract.

        Returns:
            str or None: The extracted raw string snippet containing the entire function definition,
                         or None if the file is unreadable or function pattern is not matched.
        """
        import os
        from language_config import LanguageManager
        
        full_path = os.path.normpath(os.path.join(self.project_root, relative_path))
        if not os.path.exists(full_path):
            return None

        try:
            with open(full_path, "r", encoding="utf-8") as f:
                content = f.read()
        except:
            return None

        if function_name == "GLOBAL_SCOPE":
            _, ext = os.path.splitext(relative_path)
            lm = LanguageManager()
            parser = lm.get_parser(ext)
            if parser:
                try:
                    tree = parser.parse(bytes(content, "utf-8"))
                    top_level_snippets = []
                    
                    for child in tree.root_node.children:
                        is_func_or_class = False
                        
                        if ext == ".py":
                            if child.type in ("function_definition", "class_definition"):
                                is_func_or_class = True
                        elif ext in (".js", ".jsx", ".ts", ".tsx"):
                            if child.type in ("function_declaration", "class_declaration"):
                                is_func_or_class = True
                            elif child.type == "export_statement":
                                for sub in child.children:
                                    if sub.type in ("function_declaration", "class_declaration"):
                                        is_func_or_class = True
                                        break
                            elif child.type in ("variable_declaration", "lexical_declaration"):
                                for c in child.children:
                                    if c.type == "variable_declarator":
                                        val = c.child_by_field_name("value")
                                        if val and val.type in ("arrow_function", "function_expression"):
                                            is_func_or_class = True
                                            break
                                            
                        if not is_func_or_class:
                            snippet_text = content[child.start_byte:child.end_byte]
                            top_level_snippets.append(snippet_text)
                            
                    if top_level_snippets:
                        return "\n".join(top_level_snippets)
                except Exception as e:
                    print(f"[ERROR in GLOBAL_SCOPE extraction]: {e}")
                    pass
            return None

        # PASS 1: Pre-compiled Graph Metadata Lookup (Fast Path)
        if not relative_path.endswith(".py"):
            file_key = relative_path.replace("\\", "/")
            fns = self.graph.get("functions", {}).get(file_key, [])
            if not fns:
                # Try matching with normalized paths
                for k, v in self.graph.get("functions", {}).items():
                    if os.path.normpath(k).replace("\\", "/") == os.path.normpath(file_key).replace("\\", "/"):
                        fns = v
                        break

            for fn in fns:
                if fn.get("name") == function_name:
                    start_line = fn.get("start_line")
                    end_line = fn.get("end_line")
                    if start_line is not None and end_line is not None:
                        lines = content.splitlines()
                        if 0 < start_line <= len(lines) and 0 < end_line <= len(lines):
                            return "\n".join(lines[start_line - 1:end_line])

        # PASS 2: Tree-sitter AST Parsing (Fallback Path)
        _, ext = os.path.splitext(relative_path)
        lm = LanguageManager()
        parser = lm.get_parser(ext)
        if parser:
            try:
                tree = parser.parse(bytes(content, "utf-8"))
                
                def find_func_node(node):
                    is_func_def = False
                    if ext == ".py" and node.type == "function_definition":
                        is_func_def = True
                    elif ext in (".js", ".jsx", ".ts", ".tsx"):
                        if node.type in ("function_declaration", "method_definition"):
                            is_func_def = True
                        elif node.type == "variable_declarator":
                            val_node = node.child_by_field_name("value")
                            if val_node and val_node.type in ("arrow_function", "function_expression"):
                                is_func_def = True
                        elif node.type == "pair":
                            val_node = node.child_by_field_name("value")
                            if val_node and val_node.type in ("arrow_function", "function_expression"):
                                is_func_def = True

                    if is_func_def:
                        name_node = node.child_by_field_name("name")
                        if node.type == "pair":
                            name_node = node.child_by_field_name("key")
                        if name_node:
                            try:
                                name_text = name_node.text.decode("utf-8")
                            except:
                                name_text = str(name_node.text)
                            if name_text == function_name:
                                return node

                    for child in node.children:
                        res = find_func_node(child)
                        if res:
                            return res
                    return None

                target_node = find_func_node(tree.root_node)
                if target_node:
                    return content[target_node.start_byte:target_node.end_byte]
            except Exception:
                pass

    def extract_route_statement(self, relative_path, route_path, route_method):
        """
        Reads a physical source file and extracts the exact string contents of the specified route
        registration statement using Tree-sitter AST queries.
        """
        import os
        from language_config import LanguageManager
        
        full_path = os.path.normpath(os.path.join(self.project_root, relative_path))
        if not os.path.exists(full_path):
            return None
            
        try:
            with open(full_path, "r", encoding="utf-8") as f:
                content = f.read()
        except:
            return None
            
        _, ext = os.path.splitext(relative_path)
        lm = LanguageManager()
        parser = lm.get_parser(ext)
        if not parser:
            return None
            
        try:
            tree = parser.parse(bytes(content, "utf-8"))
            
            def find_route_node(node):
                if node.type == "call_expression":
                    fn_node = node.child_by_field_name("function")
                    if fn_node and fn_node.type == "member_expression":
                        prop_node = fn_node.child_by_field_name("property")
                        if prop_node:
                            try:
                                prop_text = prop_node.text.decode("utf-8")
                            except:
                                prop_text = str(prop_node.text)
                                
                            if prop_text.lower() == route_method.lower():
                                args_node = node.child_by_field_name("arguments")
                                if args_node and args_node.named_child_count > 0:
                                    first_arg = args_node.named_children[0]
                                    if first_arg.type == "string":
                                        try:
                                            arg_text = first_arg.text.decode("utf-8")
                                        except:
                                            arg_text = str(first_arg.text)
                                        arg_val = arg_text.strip("'\"")
                                        if arg_val == route_path:
                                            parent = node.parent
                                            if parent and parent.type == "expression_statement":
                                                return parent
                                            return node
                                            
                for child in node.children:
                    res = find_route_node(child)
                    if res:
                        return res
                return None
                
            target_node = find_route_node(tree.root_node)
            if target_node:
                return content[target_node.start_byte:target_node.end_byte]
        except Exception as e:
            print(f"[ERROR in extract_route_statement]: {e}")
            
        return None

    # ==========================================================
    # EXECUTION CHAIN
    # ==========================================================

    def extract_execution_chain(

        self,

        file_path,

        function_name
    ):
        """
        Retrieves all incoming execution edges in the semantic graph that lead into the target function,
        identifying both inter-procedural route activations and standard function call origins.

        Args:
            file_path (str): The workspace-relative file path where the target function resides.
            function_name (str): The name of the target function.

        Returns:
            List[Dict]: List of step dictionaries mapping caller source nodes and edge types.
        """

        chain = []

        for edge in self.graph.get(

            "execution_edges",

            []
        ):

            from_node = edge.get("from")

            to_node = edge.get("to")

            edge_type = edge.get("type")

            # ==================================================
            # ROUTE → FUNCTION
            # ==================================================

            if (

                edge_type == "ROUTE_CALL"

                and

                to_node.get("file") == file_path

                and

                to_node.get("function") == function_name
            ):

                chain.append({

                    "type": "ROUTE",

                    "route":
                        from_node.get(
                            "route"
                        ),

                    "method":
                        from_node.get(
                            "method"
                        ),

                    "target_function":
                        function_name
                })

            # ==================================================
            # FUNCTION → FUNCTION
            # ==================================================

            elif (

                edge_type == "FUNCTION_CALL"

                and

                to_node.get("file") == file_path

                and

                to_node.get("function") == function_name
            ):

                chain.append({

                    "type": "FUNCTION_CALL",

                    "caller_file":
                        from_node.get(
                            "file"
                        ),

                    "caller_function":
                        from_node.get(
                            "function"
                        ),

                    "target_function":
                        function_name
                })

        return chain


    # ==========================================================
    # ROUTE CONTEXT
    # ==========================================================

    def extract_route_context(

        self,

        file_path,

        function_name
    ):
        """
        Queries the semantic graph for active HTTP route nodes whose endpoint execution flows
        eventually invoke or reach the target function.

        Args:
            file_path (str): The workspace-relative file path where the target function is defined.
            function_name (str): The name of the target function.

        Returns:
            List[Dict]: List of route dictionaries mapping HTTP methods and URL paths.
        """

        routes = []

        for edge in self.graph.get(

            "execution_edges",

            []
        ):

            if edge.get("type") != "ROUTE_CALL":
                continue

            to_node = edge.get("to")

            from_node = edge.get("from")

            if (

                to_node.get("file") == file_path

                and

                to_node.get("function") == function_name
            ):

                routes.append({

                    "route":
                        from_node.get(
                            "route"
                        ),

                    "method":
                        from_node.get(
                            "method"
                        )
                })

        return routes


    # ==========================================================
    # TAINT FLOW
    # ==========================================================

    def extract_taint_flow(

        self,

        function_name
    ):
        """
        Filters all identified untrusted data flows in the semantic graph to extract those
        pointing to the target function as a propagation target.

        Args:
            function_name (str): The name of the function to check taint intersections for.

        Returns:
            List[Dict]: List of taint flow records indicating source, sink, and parameter details.
        """

        flows = []

        for taint in self.graph.get(

            "taint_sources",

            []
        ):

            if (

                taint.get(
                    "target_function"
                )

                ==

                function_name
            ):

                flows.append(taint)

        return flows